version: "3.2"
services:

  sql-server-db:
    container_name: sql-server-db
    image:  mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "hardPass123"
      ACCEPT_EULA: "Y"
    volumes:
      - ./SQL/dbSetup.sql:/var/sql/createDB.sql
    # command: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P hardPass123 -i /var/sql/createDB.sql
   
  
