version: "3.2"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: custom-php:latest
    container_name: php-web-app
    volumes:
      - ./webapp:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=CINEMA
      - MYSQL_USER=user
      - MYSQL_PASSWORD=hardPass123

  mysql:
    image: mysql:5.7
    container_name: mysql-db
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./SQL:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=CINEMA
      - MYSQL_USER=user
      - MYSQL_PASSWORD=hardPass123
    command: --init-file=/docker-entrypoint-initdb.d/init.sql