USE [master]
GO
/****** Object:  Database [CINEMA]    Script Date: 22.01.2024 18:06:12 ******/
CREATE DATABASE [CINEMA]

GO
ALTER DATABASE [CINEMA] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CINEMA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CINEMA] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CINEMA] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CINEMA] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CINEMA] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CINEMA] SET ARITHABORT OFF 
GO
ALTER DATABASE [CINEMA] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CINEMA] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CINEMA] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CINEMA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CINEMA] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CINEMA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CINEMA] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CINEMA] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CINEMA] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CINEMA] SET  DISABLE_BROKER 
GO
ALTER DATABASE [CINEMA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CINEMA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CINEMA] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CINEMA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CINEMA] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CINEMA] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CINEMA] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CINEMA] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [CINEMA] SET  MULTI_USER 
GO
ALTER DATABASE [CINEMA] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CINEMA] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CINEMA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CINEMA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [CINEMA] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [CINEMA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [CINEMA] SET QUERY_STORE = OFF
GO
USE [CINEMA]
GO
/****** Object:  Table [dbo].[CINEMA_HALL]    Script Date: 22.01.2024 18:06:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CINEMA_HALL](
	[id] [int] NOT NULL,
	[name] [varchar](50) NOT NULL,
	[rows] [int] NOT NULL,
	[seats_in_row] [int] NOT NULL,
 CONSTRAINT [PK__CINEMA_H__3213E83FBE9E6579] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MOVIES]    Script Date: 22.01.2024 18:06:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MOVIES](
	[id] [int] NOT NULL,
	[title] [varchar](50) NOT NULL,
	[minutes] [int] NOT NULL,
	[description] [varchar](250) NOT NULL,
 CONSTRAINT [PK__MOVIES__3213E83F43A9068F] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RESERVATIONS]    Script Date: 22.01.2024 18:06:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RESERVATIONS](
	[id] [int] NOT NULL,
	[user_id] [int] NULL,
	[seance_id] [int] NULL,
	[seat_id] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SEANCES]    Script Date: 22.01.2024 18:06:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SEANCES](
	[id] [int] NOT NULL,
	[movie_id] [int] NOT NULL,
	[hall_id] [int] NOT NULL,
	[date] [date] NOT NULL,
	[start_time] [time](7) NOT NULL,
 CONSTRAINT [PK__SEANCES__3213E83FB72412CC] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USERS]    Script Date: 22.01.2024 18:06:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERS](
	[id] [int] NOT NULL,
	[username] [varchar](20) NOT NULL,
	[password] [varchar](20) NOT NULL,
	[admin] [bit] NOT NULL,
 CONSTRAINT [PK__USERS__3213E83FA264AE8C] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[CINEMA_HALL] ([id], [name], [rows], [seats_in_row]) VALUES (1, N'GOLD', 4, 5)
GO
INSERT [dbo].[CINEMA_HALL] ([id], [name], [rows], [seats_in_row]) VALUES (2, N'SILVER', 6, 6)
GO
INSERT [dbo].[MOVIES] ([id], [title], [minutes], [description]) VALUES (1, N'Indiana Jones', 120, N'Nowe przygody Indiany Jones''a')
GO
INSERT [dbo].[SEANCES] ([id], [movie_id], [hall_id], [date], [start_time]) VALUES (1, 1, 1, CAST(N'2024-01-28' AS Date), CAST(N'20:00:00' AS Time))
GO
INSERT [dbo].[USERS] ([id], [username], [password], [admin]) VALUES (1, N'michal', N'1234', 0)
GO
ALTER TABLE [dbo].[RESERVATIONS]  WITH CHECK ADD  CONSTRAINT [FK__RESERVATI__seanc__2F10007B] FOREIGN KEY([seance_id])
REFERENCES [dbo].[SEANCES] ([id])
GO
ALTER TABLE [dbo].[RESERVATIONS] CHECK CONSTRAINT [FK__RESERVATI__seanc__2F10007B]
GO
ALTER TABLE [dbo].[RESERVATIONS]  WITH CHECK ADD  CONSTRAINT [FK__RESERVATI__user___2E1BDC42] FOREIGN KEY([user_id])
REFERENCES [dbo].[USERS] ([id])
GO
ALTER TABLE [dbo].[RESERVATIONS] CHECK CONSTRAINT [FK__RESERVATI__user___2E1BDC42]
GO
ALTER TABLE [dbo].[SEANCES]  WITH CHECK ADD  CONSTRAINT [FK__SEANCES__hall_id__2B3F6F97] FOREIGN KEY([hall_id])
REFERENCES [dbo].[CINEMA_HALL] ([id])
GO
ALTER TABLE [dbo].[SEANCES] CHECK CONSTRAINT [FK__SEANCES__hall_id__2B3F6F97]
GO
ALTER TABLE [dbo].[SEANCES]  WITH CHECK ADD  CONSTRAINT [FK__SEANCES__movie_i__2A4B4B5E] FOREIGN KEY([movie_id])
REFERENCES [dbo].[MOVIES] ([id])
GO
ALTER TABLE [dbo].[SEANCES] CHECK CONSTRAINT [FK__SEANCES__movie_i__2A4B4B5E]
GO
USE [master]
GO
ALTER DATABASE [CINEMA] SET  READ_WRITE 
GO
